config/routes.rb
Rails.application.routes.draw do
 root "authors#index"
  resources :author do
    resources :book
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books
  validates :title, presence: true
   validates :body, presence: true, length: { minimum: 8 }
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/author_controller.rb
class AuthorController < ApplicationController
  def index
    @author = Author.all
  end
  def show
    @author = Author.find{param[:id]}
   end
  def new
    @author = Author.new
  end
  def create
    @author = Author.new(author_params)
     if @author.save
      redirect_to @author
    else
      render :new
    end
  end
   def edit
    @author = Author.find(params[:id])
  end
   def update
    @author = Author.find(params[:id])

    if @author.update(book_params)
      redirect_to @author
    else
      render :edit
    end
  end
  def destroy
    @author = Author.find(params[:id])
    @author.destroy

    redirect_to root_path
  end
     private
    def author_params
      params.require(:author).permit(:tital, :body)
    end
  
end

app/controllers/book_controller.rb
class BooksController < ApplicationController
  def create
    @author = Author.find(params[:author_id])
    @book = @author.book.create(book_params)
    redirect_to article_path(@author)
  end

  private
    def book_params
      params.require(:book).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/views/author/_form.html.erb
<%= form_with model: book do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/author/index.html.erb
<h1>Books</h1>
<ul>
   <% @books.each do |book| %> 
    <li>
     <%= link_to book.book_name, book %>

    </li>
  <% end %>
  <%= link_to "New Book", new_book_path %>

app/views/author/new.html.erb
<h1>New Author</h1>
<%= form_with model: @author do |form| %>
<div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
</div>
 <div>
    <%= form.label :author %><br>
    <%= form.text_area :author %>
 </div>
 <div>
    <%= form.submit %>
 </div>
<% end %>

app/views/author/show.html.erb
<h1> <%= @author.tital =%> </h1>
<p>  <%= @author.body =%> </p>
<ul>
  <li><%= link_to "Edit", edit_author_path(@author) %></li>
  <li><%= link_to "Destroy", author_path(@author),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></li>
</ul>
<h2>Add a book:</h2>
<%= form_with model: [ @author, @author.book.build ] do |form| %>
  <p>
    <%= form.label :book %><br>
    <%= form.text_field :book %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Library1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>